// ---------------------------------------------------------------------------------------
//                                 SpawnDev.ILGPU.WebGPU
//                        Copyright (c) 2024 SpawnDev Project
//
// File: WGSLEmulationLibrary.cs
//
// Provides WGSL helper functions for emu_f64 and emu_i64 emulation.
// emu_f64: Double-float technique using vec2<f32> (high + low)
// emu_i64: Double-word technique using vec2<u32> (low + high)
// ---------------------------------------------------------------------------------------

namespace SpawnDev.ILGPU.WebGPU.Backend
{
    /// <summary>
    /// Provides WGSL code strings for 64-bit type emulation functions.
    /// These functions are prepended to the shader when emulation is used.
    /// </summary>
    public static class WGSLEmulationLibrary
    {
        /// <summary>
        /// WGSL helper functions that materialise IEEE-754 special f32 values
        /// (positive infinity, negative infinity, quiet NaN) at runtime.
        ///
        /// WGSL has no literal form for these values AND Tint (Chrome's WGSL
        /// parser) rejects ANY expression that const-evaluates to a non-finite
        /// f32 - even when the expression is inside a function body or wraps
        /// a pipeline-override constant. After override substitution at
        /// pipeline creation, `bitcast&lt;f32&gt;(0x7F800000u)` const-folds to
        /// +Inf and Tint refuses with "value inf cannot be represented as
        /// 'f32'". So we cannot use any const-or-override-driven bit pattern.
        ///
        /// Workaround: take the bit pattern OR it with a runtime-only u32 that
        /// the const-evaluator cannot fold. `_ilgpu_runtime_zero` is a
        /// `var&lt;private&gt;` written from `local_id.x ^ local_id.x` at the
        /// top of the kernel main. The XOR-self always yields zero at
        /// runtime, but Tint does not const-fold it because `local_id` is a
        /// `@builtin(local_invocation_id)` value (runtime, varies per thread).
        /// The bitcast input is therefore non-const at compile time and the
        /// resulting +Inf / -Inf / NaN is materialised at execution time
        /// inside the function body, where producing non-finite f32 is
        /// permitted.
        ///
        /// Callsites generated by FormatFloat emit `_f32_pos_inf()` /
        /// `_f32_neg_inf()` / `_f32_qnan()` instead of an inline bitcast.
        /// </summary>
        public const string F32SpecialValueFunctions = @"
var<private> _ilgpu_runtime_zero : u32 = 0u;
fn _f32_pos_inf() -> f32 { return bitcast<f32>(0x7F800000u | _ilgpu_runtime_zero); }
fn _f32_neg_inf() -> f32 { return bitcast<f32>(0xFF800000u | _ilgpu_runtime_zero); }
fn _f32_qnan()    -> f32 { return bitcast<f32>(0x7FC00000u | _ilgpu_runtime_zero); }
";

        /// <summary>
        /// Exact f64 &lt;-&gt; IEEE-754 bit pattern and f64 &lt;-&gt; integer conversions, shared by BOTH
        /// f64 emulation modes (appended to <see cref="F64Functions"/> and
        /// <see cref="OzakiF64Functions"/>). Everything happens in the integer domain on the IEEE bit
        /// pattern; the only representation-specific step is splitting a 53-bit significand into
        /// exact f32 components (Dekker keeps two, Ozaki all three) and summing the components back.
        /// Self-contained: uses raw vec2&lt;u32&gt; (lo, hi) so an int -&gt; double conversion works even
        /// when the i64 family is not included.
        /// </summary>
        public const string F64ExactConversionFunctions = @"
// ---- exact f64 <-> bits / integer conversion core (shared by Dekker and Ozaki) ----
// BRANCH-FREE throughout (every case computed, the result chosen by select): these are inlined
// into every emulated-double load, store and conversion, and D3D's FXC (Chrome's WebGPU/WebGL
// shader compiler on Windows) compiles branches superlinearly - an early-return version made a
// kernel with 38 stores take 12.5 s to compile, and a bigger one never finished before the GPU
// watchdog killed the device.
fn _f64u_add(a: vec2<u32>, b: vec2<u32>) -> vec2<u32> {
    let lo = a.x + b.x;
    return vec2<u32>(lo, a.y + b.y + select(0u, 1u, lo < a.x));
}

fn _f64u_sub(a: vec2<u32>, b: vec2<u32>) -> vec2<u32> {
    return vec2<u32>(a.x - b.x, a.y - b.y - select(0u, 1u, a.x < b.x));
}

// 64-bit shifts, 0 <= n (n >= 64 gives 0). WGSL masks a shift amount to 5 bits, so the
// 0 / 32..63 / 64+ ranges are selected explicitly.
fn _f64u_shl(a: vec2<u32>, n: u32) -> vec2<u32> {
    let s = n & 31u;
    let small = vec2<u32>(a.x << s, (a.y << s) | select(a.x >> ((32u - s) & 31u), 0u, s == 0u));
    let r = select(small, vec2<u32>(0u, a.x << s), n >= 32u);
    return select(r, vec2<u32>(0u, 0u), n >= 64u);
}

fn _f64u_shr(a: vec2<u32>, n: u32) -> vec2<u32> {
    let s = n & 31u;
    let small = vec2<u32>((a.x >> s) | select(a.y << ((32u - s) & 31u), 0u, s == 0u), a.y >> s);
    let r = select(small, vec2<u32>(a.y >> s, 0u), n >= 32u);
    return select(r, vec2<u32>(0u, 0u), n >= 64u);
}

// Index of the highest set bit of a NON-ZERO 64-bit value.
fn _f64u_msb(a: vec2<u32>) -> u32 {
    return select(firstLeadingBit(a.x), 32u + firstLeadingBit(a.y), a.y != 0u);
}

// a >> n (n >= 1) rounded to nearest, ties to even. sticky = the true value is strictly
// greater than a (fraction below a's LSB that is not represented in a).
fn _f64u_shr_rne(a: vec2<u32>, n: u32, sticky: bool) -> vec2<u32> {
    let q = _f64u_shr(a, n);
    let h = _f64u_shr(a, n - 1u);
    let below = _f64u_shl(h, n - 1u);
    let rest = sticky || below.x != a.x || below.y != a.y;
    let up = (h.x & 1u) == 1u && (rest || (q.x & 1u) == 1u);
    return select(q, _f64u_add(q, vec2<u32>(1u, 0u)), up);
}

// Adds one lower f32 component into the magnitude accumulator (x, y) = |hi| scaled so the hi
// LSB is bit 39; z = sticky (true value strictly above the accumulator). A component with the
// sign of hi adds, one with the opposite sign subtracts (a normalized Dekker/Ozaki low word
// often has the opposite sign). Bits below the accumulator LSB are floored + sticky: in a
// normalized expansion every later component is smaller than the first dropped part, so it
// cannot move the floor.
fn _f64_acc_component(st: vec3<u32>, c: f32, hi_sign: u32, ehn: u32) -> vec3<u32> {
    let b = bitcast<u32>(c);
    let e = (b >> 23u) & 0xFFu;
    let en = max(e, 1u);
    let m = select(b & 0x7FFFFFu, (b & 0x7FFFFFu) | 0x800000u, e != 0u);
    let pos = 39 - (i32(ehn) - i32(en));
    let left = pos >= 0;
    let mid = !left && -pos < 24;
    let rs = u32(clamp(-pos, 0, 31));
    let part = select(select(vec2<u32>(0u, 0u), vec2<u32>(m >> rs, 0u), mid), _f64u_shl(vec2<u32>(m, 0u), u32(max(pos, 0))), left);
    let dropped = !left && (!mid || (m & ((1u << rs) - 1u)) != 0u);
    let acc = vec2<u32>(st.x, st.y);
    let added = _f64u_add(acc, part);
    let subbed = _f64u_sub(_f64u_sub(acc, part), vec2<u32>(select(0u, 1u, dropped), 0u));
    let next = vec3<u32>(select(subbed, added, (b & 0x80000000u) == hi_sign), select(st.z, 1u, dropped));
    let skip = (b & 0x7FFFFFFFu) == 0u || (st.z != 0u && dropped && part.x == 0u && part.y == 0u);
    return select(next, st, skip);
}

// Exact sum of up to four f32 components (hi first) as an IEEE-754 double bit pattern,
// rounded to nearest-even at 53 bits. Returns vec2<u32>(lo, hi).
fn _f64_components_to_bits(c: vec4<f32>) -> vec2<u32> {
    let hb = bitcast<u32>(c.x);
    let sign = hb & 0x80000000u;
    let eh = (hb >> 23u) & 0xFFu;
    let ehn = max(eh, 1u);
    let mh = select(hb & 0x7FFFFFu, (hb & 0x7FFFFFu) | 0x800000u, eh != 0u);
    var st = vec3<u32>(0u, mh << 7u, 0u); // mh << 39
    st = _f64_acc_component(st, c.y, sign, ehn);
    st = _f64_acc_component(st, c.z, sign, ehn);
    st = _f64_acc_component(st, c.w, sign, ehn);
    let acc = vec2<u32>(st.x, st.y);
    let p = _f64u_msb(acc);
    let big = p > 52u;
    let mr = _f64u_shr_rne(acc, p - 52u, st.z != 0u);
    let carry = (mr.y >> 21u) != 0u; // rounding carried into bit 53
    let m = select(_f64u_shl(acc, 52u - p), select(mr, _f64u_shr(mr, 1u), carry), big);
    let pf = p + select(0u, 1u, big && carry);
    let biased = pf + ehn + 834u; // (p - 62) + (ehn - 127) + 1023
    let normal = vec2<u32>(m.x, sign | (biased << 20u) | (m.y & 0xFFFFFu));
    let zero = (acc.x | acc.y) == 0u || (hb & 0x7FFFFFFFu) == 0u;
    let finite = select(normal, vec2<u32>(0u, sign), zero);
    let special = vec2<u32>(0u, sign | select(0x7FF00000u, 0x7FF80000u, (hb & 0x7FFFFFu) != 0u));
    return select(finite, special, eh == 0xFFu);
}

// 2^k * x without the f32 exponent range limiting the scale factor.
fn _f64_scale(x: f32, k: i32) -> f32 {
    return ldexp(x, k);
}

// Exact split of an IEEE-754 double (bits lo, hi) into non-overlapping f32 components:
// 24 + 24 + 5 significand bits (c.w = 0). Specials and values outside the f32 exponent range
// come back in c.x alone (the double-float representations cannot hold them anyway).
fn _f64_bits_to_components(lo: u32, hi: u32) -> vec4<f32> {
    let sign = hi & 0x80000000u;
    let exponent = (hi >> 20u) & 0x7FFu;
    let m_hi20 = hi & 0xFFFFFu;
    let e = i32(exponent) - 1023;
    let f32_exp = e + 127;
    let fe = u32(clamp(f32_exp, 1, 254));
    // M = 1.m (53 bits): c0 = bits 52..29, c1 = bits 28..5, c2 = bits 4..0
    let c0 = 0x800000u | (m_hi20 << 3u) | (lo >> 29u);
    let c1 = (lo >> 5u) & 0xFFFFFFu;
    let c2 = lo & 0x1Fu;
    let s = select(1.0, -1.0, sign != 0u);
    let f0 = bitcast<f32>(sign | (fe << 23u) | (c0 & 0x7FFFFFu));
    let normal = vec4<f32>(f0, s * _f64_scale(f32(c1), e - 47), s * _f64_scale(f32(c2), e - 52), 0.0);
    let approx = vec4<f32>(bitcast<f32>(sign | (fe << 23u) | (m_hi20 << 3u)), 0.0, 0.0, 0.0);
    let special = vec4<f32>(bitcast<f32>(sign | select(0x7F800000u, 0x7FC00000u, (m_hi20 | lo) != 0u)), 0.0, 0.0, 0.0);
    let zero = vec4<f32>(bitcast<f32>(sign), 0.0, 0.0, 0.0);
    var r = select(normal, approx, f32_exp <= 0 || f32_exp >= 255);
    r = select(r, special, exponent == 0x7FFu);
    return select(r, zero, exponent == 0u && m_hi20 == 0u && lo == 0u);
}

// Unsigned 64-bit integer -> double bits, rounded to nearest-even at 53 bits.
fn _f64_u64_to_bits(v: vec2<u32>) -> vec2<u32> {
    let p = _f64u_msb(v);
    let big = p > 52u;
    let mr = _f64u_shr_rne(v, p - 52u, false);
    let carry = (mr.y >> 21u) != 0u;
    let m = select(_f64u_shl(v, 52u - p), select(mr, _f64u_shr(mr, 1u), carry), big);
    let pf = p + select(0u, 1u, big && carry);
    return select(vec2<u32>(m.x, ((pf + 1023u) << 20u) | (m.y & 0xFFFFFu)), vec2<u32>(0u, 0u), v.x == 0u && v.y == 0u);
}

fn f64_from_u64(v: vec2<u32>) -> emu_f64 {
    let b = _f64_u64_to_bits(v);
    return f64_from_ieee754_bits(b.x, b.y);
}

fn f64_from_i64(v: vec2<u32>) -> emu_f64 {
    let neg = (v.y & 0x80000000u) != 0u;
    let b = _f64_u64_to_bits(select(v, _f64u_sub(vec2<u32>(0u, 0u), v), neg));
    return f64_from_ieee754_bits(b.x, b.y | select(0u, 0x80000000u, neg));
}

fn f64_from_u32(v: u32) -> emu_f64 {
    return f64_from_u64(vec2<u32>(v, 0u));
}

fn f64_from_i32(v: i32) -> emu_f64 {
    return f64_from_i64(vec2<u32>(bitcast<u32>(v), select(0u, 0xFFFFFFFFu, v < 0)));
}

fn _f64_bits_is_nan(b: vec2<u32>) -> bool {
    return ((b.y >> 20u) & 0x7FFu) == 0x7FFu && ((b.y & 0xFFFFFu) | b.x) != 0u;
}

// |value| truncated toward zero; z = 1 when |value| >= 2^64 (incl. infinity).
fn _f64_bits_trunc_mag(b: vec2<u32>) -> vec3<u32> {
    let exponent = (b.y >> 20u) & 0x7FFu;
    let e = exponent - 1023u; // wraps below 1023; that case is selected away
    let m = vec2<u32>(b.x, (b.y & 0xFFFFFu) | 0x100000u);
    let r = vec3<u32>(select(_f64u_shr(m, 52u - e), _f64u_shl(m, e - 52u), e >= 52u), 0u);
    let sat = select(r, vec3<u32>(0xFFFFFFFFu, 0xFFFFFFFFu, 1u), e >= 64u);
    return select(sat, vec3<u32>(0u, 0u, 0u), exponent < 1023u);
}

// double -> long, truncating toward zero and SATURATING like .NET 9+ (NaN -> 0).
fn f64_to_i64(v: emu_f64) -> vec2<u32> {
    let b = f64_to_ieee754_bits(v);
    let t = _f64_bits_trunc_mag(b);
    let neg_ovf = t.z != 0u || t.y > 0x80000000u || (t.y == 0x80000000u && t.x != 0u);
    let neg = select(_f64u_sub(vec2<u32>(0u, 0u), t.xy), vec2<u32>(0u, 0x80000000u), neg_ovf);
    let pos = select(t.xy, vec2<u32>(0xFFFFFFFFu, 0x7FFFFFFFu), t.z != 0u || t.y >= 0x80000000u);
    let r = select(pos, neg, (b.y & 0x80000000u) != 0u);
    return select(r, vec2<u32>(0u, 0u), _f64_bits_is_nan(b));
}

// double -> ulong, truncating, saturating (NaN and negatives -> 0).
fn f64_to_u64(v: emu_f64) -> vec2<u32> {
    let b = f64_to_ieee754_bits(v);
    return select(_f64_bits_trunc_mag(b).xy, vec2<u32>(0u, 0u), _f64_bits_is_nan(b) || (b.y & 0x80000000u) != 0u);
}

fn f64_to_i32(v: emu_f64) -> i32 {
    let r = f64_to_i64(v);
    let hi = bitcast<i32>(r.y);
    let r32 = select(bitcast<i32>(r.x), 2147483647, hi > 0 || (hi == 0 && r.x > 0x7FFFFFFFu));
    return select(r32, bitcast<i32>(0x80000000u), hi < -1 || (hi == -1 && r.x < 0x80000000u));
}

fn f64_to_u32(v: emu_f64) -> u32 {
    let r = f64_to_u64(v);
    return select(r.x, 0xFFFFFFFFu, r.y != 0u);
}

// ---- exact Floor / Ceiling / Round on the IEEE bit pattern ----
// Rounds the double (bits lo, hi) to an integer: toward -inf (ceil_mode false) or +inf.
fn _f64_bits_round_int(b: vec2<u32>, ceil_mode: bool) -> vec2<u32> {
    let exponent = (b.y >> 20u) & 0x7FFu;
    let neg = (b.y & 0x80000000u) != 0u;
    // |x| < 1: +-0 stays, otherwise 0 / +-1 by direction.
    let small = select(select(vec2<u32>(0u, 0u), vec2<u32>(0u, 0x3FF00000u), ceil_mode),
                       select(vec2<u32>(0u, 0xBFF00000u), vec2<u32>(0u, 0x80000000u), ceil_mode), neg);
    let small_r = select(small, b, (b.x | (b.y & 0x7FFFFFFFu)) == 0u);
    let fracbits = 1075u - exponent; // 1..52 where used
    let kept = _f64u_shl(_f64u_shr(b, fracbits), fracbits);
    let bumped = select(kept, _f64u_add(kept, _f64u_shl(vec2<u32>(1u, 0u), fracbits)), neg != ceil_mode);
    let mid = select(bumped, b, kept.x == b.x && kept.y == b.y);
    let r = select(mid, small_r, exponent < 1023u);
    return select(r, b, exponent == 0x7FFu || exponent >= 1075u); // NaN, Inf, already integral
}

// Round to the nearest integer on the IEEE bit pattern; a tie goes to EVEN (Math.Round default)
// or AWAY from zero. Rounding the hi/lo components separately is wrong: 2.5000000001 is
// 2.5 + 1e-10, and round(2.5) + round(1e-10) = 2.
fn _f64_bits_round_nearest(b: vec2<u32>, away: bool) -> vec2<u32> {
    let exponent = (b.y >> 20u) & 0x7FFu;
    let sign_only = vec2<u32>(0u, b.y & 0x80000000u);
    // 0.5 <= |x| < 1: +-1, except an exact +-0.5 rounding to even (0).
    let half_range = select(vec2<u32>(0u, sign_only.y | 0x3FF00000u), sign_only, !away && b.x == 0u && (b.y & 0xFFFFFu) == 0u);
    let fracbits = 1075u - exponent; // 1..52 where used
    let one = _f64u_shl(vec2<u32>(1u, 0u), fracbits);
    let kept = _f64u_shl(_f64u_shr(b, fracbits), fracbits);
    let frac = _f64u_sub(b, kept);
    let half_v = _f64u_shl(vec2<u32>(1u, 0u), fracbits - 1u);
    let above = frac.y > half_v.y || (frac.y == half_v.y && frac.x > half_v.x);
    let tie = frac.x == half_v.x && frac.y == half_v.y;
    let odd = ((kept.x & one.x) | (kept.y & one.y)) != 0u;
    // Sign-magnitude: adding one unit to the magnitude moves away from zero (a carry into the
    // exponent is the correct next power of two).
    let mid = select(kept, _f64u_add(kept, one), above || (tie && (away || odd)));
    var r = select(mid, half_range, exponent == 1022u);
    r = select(r, sign_only, exponent < 1022u); // |x| < 0.5 -> +-0
    return select(r, b, exponent == 0x7FFu || exponent >= 1075u); // NaN, Inf, already integral
}

// Math.IEEERemainder: x - y * RoundToEven(x / y), in the emulated precision.
fn f64_ieee_rem(a: emu_f64, b: emu_f64) -> emu_f64 {
    return f64_sub(a, f64_mul(b, f64_round_even(f64_div(a, b))));
}



// Math.CopySign: |a| with the SIGN BIT of b (the leading component carries it), so a
// negative zero or NaN sign in b is honoured - a `b >= 0` test gets -0.0 wrong.
fn f64_copysign(a: emu_f64, b: emu_f64) -> emu_f64 {
    let m = f64_abs(a);
    return select(m, f64_neg(m), (bitcast<u32>(b.x) >> 31u) != 0u);
}

// C# double % : x - y * trunc(x / y), in the emulated precision.
fn f64_rem(a: emu_f64, b: emu_f64) -> emu_f64 {
    return f64_sub(a, f64_mul(b, f64_trunc(f64_div(a, b))));
}

// Pow / Atan2 through f32 (f32 accuracy; no double-precision transcendentals). Same negative-base
// rule as the f32 pow path: |x|^y, negated for an odd integral exponent.
fn f64_pow(a: emu_f64, b: emu_f64) -> emu_f64 {
    let x = f64_to_f32(a);
    let y = f64_to_f32(b);
    return f64_from_f32(pow(abs(x), y) * select(1.0, -1.0, x < 0.0 && (abs(y) % 2.0) >= 1.0));
}

fn f64_atan2(a: emu_f64, b: emu_f64) -> emu_f64 {
    return f64_from_f32(atan2(f64_to_f32(a), f64_to_f32(b)));
}

";

        #region emu_f64 Emulation (Double-Float using vec2<f32>)

        /// <summary>
        /// WGSL type alias for emulated emu_f64.
        /// </summary>
        /// <summary>
        /// Sqrt (Karp step + one Newton), and Floor / Ceiling / Truncate / Round on the IEEE bit pattern (exact for any representation;
        /// the Ozaki family uses them). Dekker has straight-line f32 versions
        /// (<see cref="DekkerRoundingFunctions"/>).
        /// </summary>
        public const string OzakiRoundingAndSqrtFunctions = @"
// Square root: the f32 estimate y0 corrected once by (a - y0^2) / (2 y0) with y0^2 exact
// (two_prod) - about 48 bits, no divide - then one Newton step y = (y + a / y) / 2 in the full
// representation. Correctly rounded like the two divide-based Newton steps it replaces, with
// half the code (FXC compile time grows superlinearly in inlined code).
fn f64_sqrt(a: emu_f64) -> emu_f64 {
    let hi = a.x;
    let ok = hi > 0.0 && (bitcast<u32>(hi) & 0x7FFFFFFFu) != 0x7F800000u;
    let x = select(f64_from_f32(1.0), a, ok);
    let y0 = sqrt(x.x);
    let p = f64_two_prod(y0, y0);
    let r0 = f64_sub(x, emu_f64(p.x, p.y, 0.0, 0.0));
    let y1 = f64_add(f64_from_f32(y0), f64_from_f32(r0.x * (0.5 / y0)));
    let y = f64_mul(f64_add(y1, f64_div(x, y1)), f64_from_f32(0.5));
    // Negative -> NaN; +-0, +Inf and NaN are their own roots.
    let special = select(a, f64_from_f32(bitcast<f32>(0xFFC00000u | (bitcast<u32>(hi) & 0u))), hi < 0.0);
    return select(special, y, ok);
}

fn f64_floor(v: emu_f64) -> emu_f64 {
    let r = _f64_bits_round_int(f64_to_ieee754_bits(v), false);
    return f64_from_ieee754_bits(r.x, r.y);
}
fn f64_ceil(v: emu_f64) -> emu_f64 {
    let r = _f64_bits_round_int(f64_to_ieee754_bits(v), true);
    return f64_from_ieee754_bits(r.x, r.y);
}
fn f64_round_even(v: emu_f64) -> emu_f64 {
    let r = _f64_bits_round_nearest(f64_to_ieee754_bits(v), false);
    return f64_from_ieee754_bits(r.x, r.y);
}
fn f64_round_away(v: emu_f64) -> emu_f64 {
    let r = _f64_bits_round_nearest(f64_to_ieee754_bits(v), true);
    return f64_from_ieee754_bits(r.x, r.y);
}
fn f64_trunc(v: emu_f64) -> emu_f64 {
    let b = f64_to_ieee754_bits(v);
    let r = _f64_bits_round_int(b, (b.y & 0x80000000u) != 0u); // toward zero
    return f64_from_ieee754_bits(r.x, r.y);
}
";

        /// <summary>Dekker (vec2) Sqrt / Floor / Ceiling / Truncate / Round in straight-line f32 arithmetic.</summary>
        public const string DekkerRoundingFunctions = @"
// Square root by Karp's method: the f32 estimate y0 corrected by (a - y0^2) / (2 y0) with y0^2
// taken exactly (two_prod), then once more from the refined value - no double-float divides.
// Worst relative error 7.8e-15 (the two divide-based Newton steps it replaces: 1.1e-14), even
// with a 2-ULP hardware sqrt, in under half the code.
fn f64_sqrt(a: emu_f64) -> emu_f64 {
    let hi = a.x;
    let ok = hi > 0.0 && (bitcast<u32>(hi) & 0x7FFFFFFFu) != 0x7F800000u;
    let x = select(emu_f64(1.0, 0.0), a, ok);
    let y0 = sqrt(x.x);
    let r0 = f64_sub(x, f64_two_prod(y0, y0));
    let y1 = f64_add(emu_f64(y0, 0.0), emu_f64(r0.x * (0.5 / y0), 0.0));
    let r1 = f64_sub(x, f64_mul(y1, y1));
    let y = f64_add(y1, emu_f64(r1.x * (0.5 / y1.x), 0.0));
    // Negative -> NaN; +-0, +Inf and NaN are their own roots.
    let special = select(a, f64_from_f32(bitcast<f32>(0xFFC00000u | (bitcast<u32>(hi) & 0u))), hi < 0.0);
    return select(special, y, ok);
}

// Integer rounding of a normalized pair (|lo| <= ulp(hi) / 2) in f32 arithmetic: a NON-integral hi
// (|hi| < 2^23) is at least one ULP from every integer, so lo cannot carry the value across one -
// the result is hi's own; an integral hi carries the whole fraction in lo. STRAIGHT-LINE (see
// f64_to_ieee754_bits): the old versions went through the IEEE bit pattern and back, the largest
// functions in the library once FXC inlined them.
fn _f64_is_finite_hi(v: emu_f64) -> bool {
    return (bitcast<u32>(v.x) & 0x7F800000u) != 0x7F800000u;
}

// hi + k for an integral hi and an integral k (k == 0 keeps hi's zero sign).
fn _f64_int_plus(hi: f32, k: f32) -> emu_f64 {
    return select(emu_f64(hi, 0.0), f64_add(emu_f64(hi, 0.0), emu_f64(k, 0.0)), k != 0.0);
}

fn f64_floor(v: emu_f64) -> emu_f64 {
    let fh = floor(v.x);
    return select(emu_f64(fh, 0.0), _f64_int_plus(fh, floor(v.y)), fh == v.x && _f64_is_finite_hi(v));
}

fn f64_ceil(v: emu_f64) -> emu_f64 {
    let ch = ceil(v.x);
    return select(emu_f64(ch, 0.0), _f64_int_plus(ch, ceil(v.y)), ch == v.x && _f64_is_finite_hi(v));
}

fn f64_trunc(v: emu_f64) -> emu_f64 {
    return select(f64_floor(v), f64_ceil(v), v.x < 0.0);
}

// Nearest integer; a tie goes to EVEN or AWAY from zero.
fn _f64_round_nearest(v: emu_f64, away: bool) -> emu_f64 {
    let hi = v.x;
    let lo = v.y;
    // hi integral: round lo (round() is ties-to-even on lo alone; d = lo - rl is exact). On a tie
    // the other candidate is rl + 2d, chosen when hi + rl is odd (even) or nearer zero (away).
    let rl = round(lo);
    let dl = lo - rl;
    let hi_odd = hi - 2.0 * floor(hi * 0.5) != 0.0;
    let rl_odd = rl - 2.0 * floor(rl * 0.5) != 0.0;
    let other_l = rl + 2.0 * dl;
    let total_neg = hi < 0.0 || (hi == 0.0 && lo < 0.0);
    let away_l = select(other_l > rl, other_l < rl, total_neg);
    let pick_l = abs(dl) == 0.5 && select(hi_odd != rl_odd, away_l, away);
    let int_hi = _f64_int_plus(hi, select(rl, other_l, pick_l));
    // hi not integral: a .5 tie in hi is decided by lo's sign, then by the tie rule.
    let rh = round(hi);
    let dh = hi - rh;
    let other_h = rh + 2.0 * dh;
    let away_h = abs(other_h) > abs(rh);
    let pick_h = abs(dh) == 0.5 && ((dh > 0.0 && lo > 0.0) || (dh < 0.0 && lo < 0.0) || (lo == 0.0 && away && away_h));
    let frac_hi = emu_f64(select(rh, other_h, pick_h), 0.0);
    return select(frac_hi, int_hi, floor(hi) == hi && _f64_is_finite_hi(v));
}

fn f64_round_even(v: emu_f64) -> emu_f64 {
    return _f64_round_nearest(v, false);
}

fn f64_round_away(v: emu_f64) -> emu_f64 {
    return _f64_round_nearest(v, true);
}
";

        public const string F64TypeAlias = "alias emu_f64 = vec2<f32>;";

        /// <summary>
        /// WGSL helper functions for emu_f64 emulation.
        /// Uses the double-float technique where emu_f64 = high + low.
        /// </summary>
        public const string F64Functions = @"
// ============================================================================
// emu_f64 Emulation Functions (Double-Float: vec2<f32> where x=high, y=low)
// ============================================================================

// --- IEEE 754 double bits <-> double-float (hi, lo) ---
// Exact split of the 53-bit significand (_f64_bits_to_components); the 29 bits below hi are
// rounded to nearest into lo - the representation keeps ~48 bits.
fn f64_from_ieee754_bits(lo: u32, hi: u32) -> emu_f64 {
    let c = _f64_bits_to_components(lo, hi);
    let l = c.y + c.z;
    let s = c.x + l;
    // c.x alone when exact, zero, Inf or NaN (the error term of an Inf would be NaN).
    return select(emu_f64(s, l - (s - c.x)), emu_f64(c.x, 0.0), c.y == 0.0 && c.z == 0.0);
}

// Store emu_f64 back to IEEE 754 bits: exact sum of hi + lo (lo of EITHER sign - the old
// version OR'ed |lo| into the mantissa, so 33554431.0 + 0.0 stored as 33554433.0).
// Exact IEEE-754 bits of the pair hi + lo, rounded to nearest-even. hi's own bits, then lo as a
// whole number of double ULPs added to the magnitude bits. STRAIGHT-LINE on purpose: this is
// inlined into every emulated-double store, and D3D's FXC (Chrome's WebGPU/WebGL shader
// compiler on Windows) compiles branches superlinearly - the branchy generic normaliser
// (_f64_components_to_bits) made 38 stores take 12.5 s to compile and a 19-op kernel with a
// NoInlining helper over 10 minutes, which the GPU watchdog kills (device lost). This: 0.69 s.
fn f64_to_ieee754_bits(v: emu_f64) -> vec2<u32> {
    // TwoSum renormalisation: afterwards |lo| <= ulp(hi) / 2, whatever produced the pair.
    let s = v.x + v.y;
    let bb = s - v.x;
    let e = (v.x - (s - bb)) + (v.y - bb);
    let s_finite = (bitcast<u32>(s) & 0x7F800000u) != 0x7F800000u;
    let hi = select(v.x, s, s_finite);
    let lo = select(0.0, e, s_finite);
    let hb = bitcast<u32>(hi);
    let sign = hb & 0x80000000u;
    let eh = (hb >> 23u) & 0xFFu;
    let mant = hb & 0x7FFFFFu;
    // hi as a double. A subnormal hi (eh == 0) normalises: value = mant * 2^-149.
    let p = firstLeadingBit(mant);
    let sub_shift = 52u - p;
    let sub_w_hi = select(mant >> ((32u - sub_shift) & 31u), mant << ((sub_shift - 32u) & 31u), sub_shift >= 32u);
    let sub_w_lo = select(mant << (sub_shift & 31u), 0u, sub_shift >= 32u);
    let is_sub = eh == 0u;
    let w_hi = select(((eh + 896u) << 20u) | (mant >> 3u), ((p + 874u) << 20u) | (sub_w_hi & 0xFFFFFu), is_sub);
    let w_lo = select((mant & 7u) << 29u, sub_w_lo, is_sub);
    // lo as a whole number of double ULPs of hi (a power-of-two scale, so exact in f32), added to
    // or subtracted from the magnitude bits: consecutive doubles have consecutive bit patterns.
    // Below an exact power of two the ULP halves, so a shrinking lo counts half-size ULPs.
    let down = lo != 0.0 && ((bitcast<u32>(lo) ^ hb) & 0x80000000u) != 0u;
    let sc = select(179, 180, down && mant == 0u) - i32(eh);
    let sc1 = sc / 2;
    let lm = abs(lo) * bitcast<f32>(u32(sc1 + 127) << 23u) * bitcast<f32>(u32(sc - sc1 + 127) << 23u);
    let li = floor(lm);
    let frac = lm - li;
    let liu = u32(li);
    // Round to nearest, ties to even (w_lo +/- liu has the parity of w_lo + liu).
    let k = liu + select(0u, 1u, frac > 0.5 || (frac == 0.5 && ((w_lo + liu) & 1u) == 1u));
    let up = vec2<u32>(w_lo + k, w_hi + select(0u, 1u, w_lo + k < w_lo));
    let dn = vec2<u32>(w_lo - k, w_hi - select(0u, 1u, w_lo < k));
    let mag = select(up, dn, down);
    let special = select(0x7FF00000u, 0x7FF80000u, mant != 0u);
    // A zero keeps v.x's sign when v.x is itself the zero (-0.0 loads as (-0, +0), and TwoSum
    // would make that +0); a zero from x + (-x) is +0.
    let zero_sign = select(sign, bitcast<u32>(v.x) & 0x80000000u, v.x == 0.0);
    let finite = select(vec2<u32>(mag.x, sign | mag.y), vec2<u32>(0u, zero_sign), (hb & 0x7FFFFFFFu) == 0u);
    return select(finite, vec2<u32>(0u, sign | special), eh == 0xFFu);
}


// Create emu_f64 from a single f32 value
fn f64_from_f32(v: f32) -> emu_f64 {
    return emu_f64(v, 0.0);
}

// Convert emu_f64 back to f32 (loses precision)
fn f64_to_f32(v: emu_f64) -> f32 {
    return v.x + v.y;
}

// Create emu_f64 from high and low components
fn f64_new(hi: f32, lo: f32) -> emu_f64 {
    return emu_f64(hi, lo);
}

// emu_f64 negation
fn f64_neg(a: emu_f64) -> emu_f64 {
    return emu_f64(-a.x, -a.y);
}

fn f64_add(a: emu_f64, b: emu_f64) -> emu_f64 {
    // A non-finite sum returns the IEEE result (the error terms would compute Inf - Inf = NaN).
    // select, not an early return: FXC compiles branches superlinearly (see f64_to_ieee754_bits).
    let s = a.x + b.x;
    let v = s - a.x;
    let e = (a.x - (s - v)) + (b.x - v) + a.y + b.y;
    let z_hi = s + e;
    let z_lo = e - (z_hi - s);
    return select(emu_f64(z_hi, z_lo), emu_f64(s, 0.0), (bitcast<u32>(s) & 0x7F800000u) == 0x7F800000u);
}

// emu_f64 subtraction
fn f64_sub(a: emu_f64, b: emu_f64) -> emu_f64 {
    return f64_add(a, f64_neg(b));
}

// Helper: split f32 into high and low parts for multiplication
fn f64_split(a: f32) -> vec2<f32> {
    let c = 4097.0 * a;  // 2^12 + 1
    let a_hi = c - (c - a);
    let a_lo = a - a_hi;
    return vec2<f32>(a_hi, a_lo);
}

// Helper: two-product algorithm (exact a*b = p + e)
fn f64_two_prod(a: f32, b: f32) -> emu_f64 {
    let p = a * b;
    let a_s = f64_split(a);
    let b_s = f64_split(b);
    let e = ((a_s.x * b_s.x - p) + a_s.x * b_s.y + a_s.y * b_s.x) + a_s.y * b_s.y;
    return emu_f64(p, e);
}

fn f64_mul(a: emu_f64, b: emu_f64) -> emu_f64 {
    // Non-finite product: the IEEE result (see f64_add).
    let p = f64_two_prod(a.x, b.x);
    let e = a.x * b.y + a.y * b.x + p.y;
    let z_hi = p.x + e;
    let z_lo = e - (z_hi - p.x);
    return select(emu_f64(z_hi, z_lo), emu_f64(p.x, 0.0), (bitcast<u32>(p.x) & 0x7F800000u) == 0x7F800000u);
}

fn f64_div(a: emu_f64, b: emu_f64) -> emu_f64 {
    // Non-finite quotient or divisor: the IEEE result (see f64_add).
    let q = a.x / b.x;
    let r = f64_sub(a, f64_mul(b, f64_from_f32(q)));
    let q2 = r.x / b.x;
    let non_finite = (bitcast<u32>(q) & 0x7F800000u) == 0x7F800000u || (bitcast<u32>(b.x) & 0x7F800000u) == 0x7F800000u;
    return select(f64_add(f64_from_f32(q), f64_from_f32(q2)), emu_f64(q, 0.0), non_finite);
}

// emu_f64 comparison helpers - IEEE-strict NaN handling.
//
// Background: the f32 == / < / > operators in WGSL are spec'd to return
// FALSE if either operand is NaN, but Tint / Chrome / some GPU drivers
// have been observed to return TRUE under unordered-comparison semantics
// for f32 NaN compares. Diagnosed 2026-04-29 against
// `BackendTestBase.DoubleNaNComparisonTest` where NaN_a == NaN_b returned
// TRUE on both Dekker and Ozaki paths despite distinct buffer-loaded
// NaN values. To be IEEE-strict regardless of implementation we detect
// NaN by f32 bit pattern (exp == 0xFF && mantissa != 0) and force the
// IEEE result for ordered comparisons.
fn _f32_is_nan_bits(v: f32) -> bool {
    let bits = bitcast<u32>(v);
    return ((bits & 0x7F800000u) == 0x7F800000u) && ((bits & 0x007FFFFFu) != 0u);
}

// emu_f64 comparison: less than (IEEE: FALSE if either operand is NaN)
fn f64_lt(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x < b.x) || (a.x == b.x && a.y < b.y));
}

// emu_f64 comparison: less than or equal (IEEE: FALSE if either is NaN)
fn f64_le(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x < b.x) || (a.x == b.x && a.y <= b.y));
}

// emu_f64 comparison: greater than (IEEE: FALSE if either is NaN)
fn f64_gt(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x > b.x) || (a.x == b.x && a.y > b.y));
}

// emu_f64 comparison: greater than or equal (IEEE: FALSE if either is NaN)
fn f64_ge(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x > b.x) || (a.x == b.x && a.y >= b.y));
}

// emu_f64 comparison: equal (IEEE: FALSE if either is NaN)
fn f64_eq(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && (a.x == b.x && a.y == b.y);
}

// emu_f64 IEEE IsNaN: detect f32 NaN bit pattern in high lane (avoid relying
// on `v.x != v.x` which under unordered-compare semantics may not detect NaN).
fn f64_is_nan(v: emu_f64) -> bool {
    return _f32_is_nan_bits(v.x);
}

// emu_f64 IEEE IsInfinity: high lane carries f32 +Inf / -Inf bit pattern
// (exp == 0xFF, mantissa == 0). Detect by bit pattern to avoid implementation-
// dependent NaN comparison semantics.
fn f64_is_inf(v: emu_f64) -> bool {
    let bits = bitcast<u32>(v.x);
    return (bits & 0x7FFFFFFFu) == 0x7F800000u;
}

// emu_f64 comparison: not equal (IEEE: TRUE if either operand is NaN)
fn f64_ne(a: emu_f64, b: emu_f64) -> bool {
    return (_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) || (a.x != b.x || a.y != b.y);
}

fn f64_abs(a: emu_f64) -> emu_f64 {
    return select(a, f64_neg(a), a.x < 0.0 || (a.x == 0.0 && a.y < 0.0));
}

fn f64_min(a: emu_f64, b: emu_f64) -> emu_f64 {
    return select(b, a, f64_lt(a, b));
}

fn f64_max(a: emu_f64, b: emu_f64) -> emu_f64 {
    return select(b, a, f64_gt(a, b));
}
" + F64ExactConversionFunctions + DekkerRoundingFunctions;

        #endregion

        #region emu_i64 Emulation (Double-Word using vec2<u32>)

        /// <summary>
        /// WGSL type alias for emulated emu_i64.
        /// x = low 32 bits, y = high 32 bits (little-endian style)
        /// </summary>
        public const string I64TypeAlias = "alias emu_i64 = vec2<u32>;";

        /// <summary>
        /// WGSL type alias for emulated emu_u64.
        /// </summary>
        public const string U64TypeAlias = "alias emu_u64 = vec2<u32>;";

        /// <summary>
        /// WGSL helper functions for emu_i64/emu_u64 emulation.
        /// Uses double-word technique where emu_i64 = (low, high).
        /// </summary>
        public const string I64Functions = @"
// ============================================================================
// emu_i64/emu_u64 Emulation Functions (Double-Word: vec2<u32> where x=low, y=high)
// ============================================================================

// Create emu_i64 from i32 (sign-extend)
fn i64_from_i32(v: i32) -> emu_i64 {
    let lo = bitcast<u32>(v);
    let hi = select(0u, 0xFFFFFFFFu, v < 0);
    return emu_i64(lo, hi);
}

// Create emu_u64 from u32
fn u64_from_u32(v: u32) -> emu_u64 {
    return emu_u64(v, 0u);
}

// Convert emu_i64 to i32 (truncate)
fn i64_to_i32(v: emu_i64) -> i32 {
    return bitcast<i32>(v.x);
}

// Convert emu_u64 to u32 (truncate)
fn u64_to_u32(v: emu_u64) -> u32 {
    return v.x;
}

// Create emu_i64 from low and high u32 parts
fn i64_new(lo: u32, hi: u32) -> emu_i64 {
    return emu_i64(lo, hi);
}

// emu_i64/emu_u64 addition with carry
fn i64_add(a: emu_i64, b: emu_i64) -> emu_i64 {
    let lo = a.x + b.x;
    let carry = select(0u, 1u, lo < a.x);
    let hi = a.y + b.y + carry;
    return emu_i64(lo, hi);
}

// emu_u64 addition (same as i64_add for two's complement)
fn u64_add(a: emu_u64, b: emu_u64) -> emu_u64 {
    return i64_add(a, b);
}

// emu_i64/emu_u64 subtraction with borrow
fn i64_sub(a: emu_i64, b: emu_i64) -> emu_i64 {
    let borrow = select(0u, 1u, a.x < b.x);
    let lo = a.x - b.x;
    let hi = a.y - b.y - borrow;
    return emu_i64(lo, hi);
}

// emu_i64 negation (two's complement)
fn i64_neg(a: emu_i64) -> emu_i64 {
    let inv = emu_i64(~a.x, ~a.y);
    return i64_add(inv, emu_i64(1u, 0u));
}

// emu_u64 multiplication (full 64x64 -> 64-bit result, ignoring overflow)
fn u64_mul(a: emu_u64, b: emu_u64) -> emu_u64 {
    // Split into 16-bit parts for WGSL compatibility
    let a_lo = a.x & 0xFFFFu;
    let a_hi = a.x >> 16u;
    let b_lo = b.x & 0xFFFFu;
    let b_hi = b.x >> 16u;
    
    // Partial products
    let p0 = a_lo * b_lo;
    let p1 = a_lo * b_hi;
    let p2 = a_hi * b_lo;
    let p3 = a_hi * b_hi;
    
    // Combine low parts
    let mid = (p0 >> 16u) + (p1 & 0xFFFFu) + (p2 & 0xFFFFu);
    let lo = (p0 & 0xFFFFu) | ((mid & 0xFFFFu) << 16u);
    
    // Combine high parts
    let hi = p3 + (p1 >> 16u) + (p2 >> 16u) + (mid >> 16u) + a.x * b.y + a.y * b.x;
    
    return emu_u64(lo, hi);
}

// emu_i64 multiplication (uses u64_mul internally)
fn i64_mul(a: emu_i64, b: emu_i64) -> emu_i64 {
    let neg_a = (a.y & 0x80000000u) != 0u;
    let neg_b = (b.y & 0x80000000u) != 0u;
    var abs_a = a;
    var abs_b = b;
    if (neg_a) { abs_a = i64_neg(a); }
    if (neg_b) { abs_b = i64_neg(b); }
    var result = u64_mul(abs_a, abs_b);
    if (neg_a != neg_b) { result = i64_neg(result); }
    return result;
}

// Bitwise AND
fn i64_and(a: emu_i64, b: emu_i64) -> emu_i64 {
    return emu_i64(a.x & b.x, a.y & b.y);
}

// Bitwise OR
fn i64_or(a: emu_i64, b: emu_i64) -> emu_i64 {
    return emu_i64(a.x | b.x, a.y | b.y);
}

// Bitwise XOR
fn i64_xor(a: emu_i64, b: emu_i64) -> emu_i64 {
    return emu_i64(a.x ^ b.x, a.y ^ b.y);
}

// Bitwise NOT
fn i64_not(a: emu_i64) -> emu_i64 {
    return emu_i64(~a.x, ~a.y);
}

// Left shift (0 <= shift < 64)
fn i64_shl(a: emu_i64, shift: u32) -> emu_i64 {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return emu_i64(0u, 0u); }
    if (shift >= 32u) {
        return emu_i64(0u, a.x << (shift - 32u));
    }
    let lo = a.x << shift;
    let hi = (a.y << shift) | (a.x >> (32u - shift));
    return emu_i64(lo, hi);
}

// Logical right shift (0 <= shift < 64)
fn u64_shr(a: emu_u64, shift: u32) -> emu_u64 {
    if (shift == 0u) { return a; }
    if (shift >= 64u) { return emu_u64(0u, 0u); }
    if (shift >= 32u) {
        return emu_u64(a.y >> (shift - 32u), 0u);
    }
    let lo = (a.x >> shift) | (a.y << (32u - shift));
    let hi = a.y >> shift;
    return emu_u64(lo, hi);
}

// Arithmetic right shift (sign-extending)
fn i64_shr(a: emu_i64, shift: u32) -> emu_i64 {
    if (shift == 0u) { return a; }
    let sign = a.y & 0x80000000u;
    if (shift >= 64u) {
        let fill = select(0u, 0xFFFFFFFFu, sign != 0u);
        return emu_i64(fill, fill);
    }
    if (shift >= 32u) {
        // Arithmetic right shift - need to use signed integer then convert back
        let signed_y = bitcast<i32>(a.y);
        let shift_amt = shift - 32u;
        let shifted = signed_y >> shift_amt;
        let lo = bitcast<u32>(shifted);
        let hi = select(0u, 0xFFFFFFFFu, sign != 0u);
        return emu_i64(lo, hi);
    }
    let lo = (a.x >> shift) | (a.y << (32u - shift));
    // Arithmetic right shift on high word
    let signed_y = bitcast<i32>(a.y);
    let shifted = signed_y >> shift;
    let hi = bitcast<u32>(shifted);
    return emu_i64(lo, hi);
}

// Signed comparison: less than
fn i64_lt(a: emu_i64, b: emu_i64) -> bool {
    let a_neg = (a.y & 0x80000000u) != 0u;
    let b_neg = (b.y & 0x80000000u) != 0u;
    if (a_neg && !b_neg) { return true; }
    if (!a_neg && b_neg) { return false; }
    // Same sign: compare as unsigned
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Signed comparison: less than or equal
fn i64_le(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(a, b) || i64_eq(a, b);
}

// Signed comparison: greater than
fn i64_gt(a: emu_i64, b: emu_i64) -> bool {
    return i64_lt(b, a);
}

// Signed comparison: greater than or equal
fn i64_ge(a: emu_i64, b: emu_i64) -> bool {
    return !i64_lt(a, b);
}

// Comparison: equal
fn i64_eq(a: emu_i64, b: emu_i64) -> bool {
    return a.x == b.x && a.y == b.y;
}

// Comparison: not equal
fn i64_ne(a: emu_i64, b: emu_i64) -> bool {
    return a.x != b.x || a.y != b.y;
}

// Unsigned comparison: less than
fn u64_lt(a: emu_u64, b: emu_u64) -> bool {
    if (a.y != b.y) { return a.y < b.y; }
    return a.x < b.x;
}

// Unsigned comparison: less than or equal
fn u64_le(a: emu_u64, b: emu_u64) -> bool {
    return u64_lt(a, b) || i64_eq(a, b);
}

// Unsigned comparison: greater than
fn u64_gt(a: emu_u64, b: emu_u64) -> bool {
    return u64_lt(b, a);
}

// Unsigned comparison: greater than or equal
fn u64_ge(a: emu_u64, b: emu_u64) -> bool {
    return !u64_lt(a, b);
}

// Signed i64 minimum
fn i64_min(a: emu_i64, b: emu_i64) -> emu_i64 {
    if (i64_lt(a, b)) { return a; }
    return b;
}

// Signed i64 maximum
fn i64_max(a: emu_i64, b: emu_i64) -> emu_i64 {
    if (i64_gt(a, b)) { return a; }
    return b;
}

// Unsigned u64 minimum
fn u64_min(a: emu_u64, b: emu_u64) -> emu_u64 {
    if (u64_lt(a, b)) { return a; }
    return b;
}

// Unsigned u64 maximum
fn u64_max(a: emu_u64, b: emu_u64) -> emu_u64 {
    if (u64_gt(a, b)) { return a; }
    return b;
}

// emu_i64 absolute value
fn i64_abs(a: emu_i64) -> emu_i64 {
    if ((a.y & 0x80000000u) != 0u) {
        return i64_neg(a);
    }
    return a;
}

// Index of the highest set bit of a NON-ZERO 64-bit value.
fn _u64_msb(a: emu_u64) -> u32 {
    if (a.y != 0u) { return 32u + firstLeadingBit(a.y); }
    return firstLeadingBit(a.x);
}

// ulong -> float, rounded to nearest-even (was: low 32 bits only).
fn u64_to_f32(v: emu_u64) -> f32 {
    if (v.x == 0u && v.y == 0u) { return 0.0; }
    var p = _u64_msb(v);
    if (p <= 23u) { return f32(v.x); }
    let n = p - 23u;
    var mant = u64_shr(v, n).x;
    let half_bit = u64_shr(v, n - 1u).x & 1u;
    let below = i64_shl(u64_shr(v, n - 1u), n - 1u);
    let rest = below.x != v.x || below.y != v.y;
    if (half_bit == 1u && (rest || (mant & 1u) == 1u)) {
        mant = mant + 1u;
        if (mant == 0x1000000u) { mant = 0x800000u; p = p + 1u; }
    }
    return bitcast<f32>(((p + 127u) << 23u) | (mant & 0x7FFFFFu));
}

fn i64_to_f32(v: emu_i64) -> f32 {
    if ((v.y & 0x80000000u) != 0u) { return -u64_to_f32(i64_neg(v)); }
    return u64_to_f32(v);
}

// float -> long, truncating, saturating like .NET 9+ (NaN -> 0).
fn f32_to_i64(f: f32) -> emu_i64 {
    let b = bitcast<u32>(f);
    let exponent = (b >> 23u) & 0xFFu;
    if (exponent == 0xFFu && (b & 0x7FFFFFu) != 0u) { return emu_i64(0u, 0u); }
    let neg = (b & 0x80000000u) != 0u;
    if (exponent < 127u) { return emu_i64(0u, 0u); }
    let e = exponent - 127u;
    if (e >= 63u) { return select(emu_i64(0xFFFFFFFFu, 0x7FFFFFFFu), emu_i64(0u, 0x80000000u), neg); }
    let m = emu_i64((b & 0x7FFFFFu) | 0x800000u, 0u);
    var r = m;
    if (e >= 23u) { r = i64_shl(m, e - 23u); } else { r = u64_shr(m, 23u - e); }
    if (neg) { return i64_neg(r); }
    return r;
}

// float -> ulong, truncating, saturating (NaN and negatives -> 0).
fn f32_to_u64(f: f32) -> emu_u64 {
    let b = bitcast<u32>(f);
    let exponent = (b >> 23u) & 0xFFu;
    if ((exponent == 0xFFu && (b & 0x7FFFFFu) != 0u) || (b & 0x80000000u) != 0u || exponent < 127u) { return emu_u64(0u, 0u); }
    let e = exponent - 127u;
    if (e >= 64u) { return emu_u64(0xFFFFFFFFu, 0xFFFFFFFFu); }
    let m = emu_u64((b & 0x7FFFFFu) | 0x800000u, 0u);
    if (e >= 23u) { return i64_shl(m, e - 23u); }
    return u64_shr(m, 23u - e);
}

";

        #endregion

        #region emu_f64 Emulation (Ozaki Scheme using vec4<f32>)

        /// <summary>
        /// WGSL type alias for Ozaki emulated emu_f64.
        /// </summary>
        public const string OzakiF64TypeAlias = "alias emu_f64 = vec4<f32>;";

        /// <summary>
        /// WGSL helper functions for Ozaki emu_f64 emulation.
        /// </summary>
        public const string OzakiF64Functions = @"
// ============================================================================
// emu_f64 Emulation Functions (Ozaki Scheme: vec4<f32>)
// Implementing Quad-Double arithmetic based on Hida, Li, and Bailey's qd library.
// ============================================================================

// IEEE-strict NaN detection by f32 bit pattern. Comparison primitives use
// this instead of relying on `x != x` because some WGSL implementations
// (Tint / Chrome / certain GPU drivers) use unordered semantics on f32
// `==` / `<` / `>` which makes those operators return TRUE in the
// presence of NaN. See `BackendTestBase.DoubleNaNComparisonTest`.
fn _f32_is_nan_bits(v: f32) -> bool {
    let bits = bitcast<u32>(v);
    return ((bits & 0x7F800000u) == 0x7F800000u) && ((bits & 0x007FFFFFu) != 0u);
}

fn f32_two_sum(a: f32, b: f32) -> vec2<f32> {
    let s = a + b;
    let v = s - a;
    let e = (a - (s - v)) + (b - v);
    return vec2<f32>(s, e);
}

fn f32_quick_two_sum(a: f32, b: f32) -> vec2<f32> {
    let s = a + b;
    let e = b - (s - a);
    return vec2<f32>(s, e);
}

fn f32_three_sum(a: f32, b: f32, c: f32) -> vec3<f32> {
    let ts1 = f32_two_sum(a, b);
    let t1 = ts1.x; let t2 = ts1.y;
    
    let ts2 = f32_two_sum(c, t1);
    let out_a = ts2.x; let t3 = ts2.y;
    
    let ts3 = f32_two_sum(t2, t3);
    let out_b = ts3.x; let out_c = ts3.y;
    
    return vec3<f32>(out_a, out_b, out_c);
}

fn f32_three_sum2(a: f32, b: f32, c: f32) -> vec3<f32> {
    let ts1 = f32_two_sum(a, b);
    let t1 = ts1.x; let t2 = ts1.y;
    
    let ts2 = f32_two_sum(c, t1);
    let out_a = ts2.x; let t3 = ts2.y;
    
    let out_b = t2 + t3;
    let out_c = ts2.y; 
    return vec3<f32>(out_a, out_b, out_c);
}

fn f32_quick_renorm(c: vec4<f32>, e: f32) -> vec4<f32> {
    var c0 = c.x; var c1 = c.y; var c2 = c.z; var c3 = c.w; var c4 = e;
    
    let ts1 = f32_quick_two_sum(c3, c4);
    var s = ts1.x; var t3 = ts1.y;
    
    let ts2 = f32_quick_two_sum(c2, s);
    s = ts2.x; var t2 = ts2.y;
    
    let ts3 = f32_quick_two_sum(c1, s);
    s = ts3.x; var t1 = ts3.y;
    
    let ts4 = f32_quick_two_sum(c0, s);
    c0 = ts4.x; var t0 = ts4.y;
    
    let ts5 = f32_quick_two_sum(t2, t3);
    s = ts5.x; t2 = ts5.y;
    
    let ts6 = f32_quick_two_sum(t1, s);
    s = ts6.x; t1 = ts6.y;
    
    let ts7 = f32_quick_two_sum(t0, s);
    c1 = ts7.x; t0 = ts7.y;
    
    let ts8 = f32_quick_two_sum(t1, t2);
    s = ts8.x; t1 = ts8.y;
    
    let ts9 = f32_quick_two_sum(t0, s);
    c2 = ts9.x; t0 = ts9.y;
    
    c3 = t0 + t1;
    
    return vec4<f32>(c0, c1, c2, c3);
}

// --- IEEE 754 double bits <-> quad-float ---
// Exact: the 53-bit significand becomes three non-overlapping f32 components (24 + 24 + 5
// bits). The old version kept only two (dropping 5 significand bits) and stored back from x
// and y alone, OR'ing |y| into the mantissa regardless of its sign.
fn f64_from_ieee754_bits(lo: u32, hi: u32) -> emu_f64 {
    let c = _f64_bits_to_components(lo, hi);
    return select(f32_quick_renorm(c, 0.0), c, c.y == 0.0 && c.z == 0.0);
}

fn f64_to_ieee754_bits(v: emu_f64) -> vec2<u32> {
    return _f64_components_to_bits(v);
}


fn f64_from_f32(v: f32) -> emu_f64 {
    return emu_f64(v, 0.0, 0.0, 0.0);
}

fn f64_to_f32(v: emu_f64) -> f32 {
    return v.x + v.y + v.z + v.w;
}

fn f64_new(hi: f32, lo: f32) -> emu_f64 {
    return emu_f64(hi, lo, 0.0, 0.0);
}

fn f64_neg(a: emu_f64) -> emu_f64 {
    return emu_f64(-a.x, -a.y, -a.z, -a.w);
}

fn f64_add(a: emu_f64, b: emu_f64) -> emu_f64 {
    // Non-finite result (or divisor): the error-term arithmetic below would compute
    // Inf - Inf = NaN (Inf + 1 came out NaN). Return the IEEE result directly.
    let _nf = a.x + b.x;
    let _nf_hit = (bitcast<u32>(_nf) & 0x7F800000u) == 0x7F800000u;
    var s0 = a.x + b.x;
    var s1 = a.y + b.y;
    var s2 = a.z + b.z;
    var s3 = a.w + b.w;

    let v0 = s0 - a.x;
    let v1 = s1 - a.y;
    let v2 = s2 - a.z;
    let v3 = s3 - a.w;

    let u0 = s0 - v0;
    let u1 = s1 - v1;
    let u2 = s2 - v2;
    let u3 = s3 - v3;

    let w0 = a.x - u0;
    let w1 = a.y - u1;
    let w2 = a.z - u2;
    let w3 = a.w - u3;

    let uu0 = b.x - v0;
    let uu1 = b.y - v1;
    let uu2 = b.z - v2;
    let uu3 = b.w - v3;

    var t0 = w0 + uu0;
    var t1 = w1 + uu1;
    var t2 = w2 + uu2;
    var t3 = w3 + uu3;

    let ts1 = f32_two_sum(s1, t0);
    s1 = ts1.x; t0 = ts1.y;
    
    let ts2 = f32_three_sum(s2, t0, t1);
    s2 = ts2.x; t0 = ts2.y; t1 = ts2.z;
    
    let ts3 = f32_three_sum2(s3, t0, t2);
    s3 = ts3.x; t0 = ts3.y; t2 = ts3.z;
    
    t0 = t0 + t1 + t3;

    return select(f32_quick_renorm(vec4<f32>(s0, s1, s2, s3), t0), emu_f64(_nf, 0.0, 0.0, 0.0), _nf_hit);
}

fn f64_sub(a: emu_f64, b: emu_f64) -> emu_f64 {
    return f64_add(a, f64_neg(b));
}

fn f64_split(a: f32) -> vec2<f32> {
    let c = 4097.0 * a;
    let a_hi = c - (c - a);
    let a_lo = a - a_hi;
    return vec2<f32>(a_hi, a_lo);
}

fn f64_two_prod(a: f32, b: f32) -> vec2<f32> {
    let p = a * b;
    let a_s = f64_split(a);
    let b_s = f64_split(b);
    let e = ((a_s.x * b_s.x - p) + a_s.x * b_s.y + a_s.y * b_s.x) + a_s.y * b_s.y;
    return vec2<f32>(p, e);
}

fn f64_mul(a: emu_f64, b: emu_f64) -> emu_f64 {
    // Non-finite result (or divisor): the error-term arithmetic below would compute
    // Inf - Inf = NaN (Inf + 1 came out NaN). Return the IEEE result directly.
    let _nf = a.x * b.x;
    let _nf_hit = (bitcast<u32>(_nf) & 0x7F800000u) == 0x7F800000u;
    let pt0 = f64_two_prod(a.x, b.x); let p0 = pt0.x; var q0 = pt0.y;
    let pt1 = f64_two_prod(a.x, b.y); let p1 = pt1.x; var q1 = pt1.y;
    let pt2 = f64_two_prod(a.y, b.x); var p2 = pt2.x; var q2 = pt2.y;
    let pt3 = f64_two_prod(a.x, b.z); var p3 = pt3.x; var q3 = pt3.y;
    let pt4 = f64_two_prod(a.y, b.y); var p4 = pt4.x; var q4 = pt4.y;
    let pt5 = f64_two_prod(a.z, b.x); var p5 = pt5.x; var q5 = pt5.y;

    var ts1 = f32_three_sum(p1, p2, q0);
    var np1 = ts1.x; p2 = ts1.y; var nq0 = ts1.z;
    
    var ts2 = f32_three_sum(p2, q1, q2);
    var np2 = ts2.x; q1 = ts2.y; q2 = ts2.z;
    
    var ts3 = f32_three_sum(p3, p4, p5);
    p3 = ts3.x; p4 = ts3.y; p5 = ts3.z;
    
    var ts4 = f32_two_sum(np2, p3);
    var s0 = ts4.x; var t0 = ts4.y;
    
    var ts5 = f32_two_sum(q1, p4);
    var s1 = ts5.x; var t1 = ts5.y;
    
    var s2 = q2 + p5;
    
    var ts6 = f32_two_sum(s1, t0);
    s1 = ts6.x; t0 = ts6.y;
    
    s2 += (t0 + t1);
    
    s1 += a.x*b.w + a.y*b.z + a.z*b.y + a.w*b.x + nq0 + q3 + q4 + q5;
    
    return select(f32_quick_renorm(vec4<f32>(p0, np1, s0, s1), s2), emu_f64(_nf, 0.0, 0.0, 0.0), _nf_hit);
}

// Quad-float times a single f32 (the QD library's qd_real * double): three two_prods instead of
// the full product's six plus its three_sum tree. Division's correction steps multiply by one
// f32 quotient digit each, and the full f64_mul made f64_div the largest function FXC inlined.
fn _f64_mul_f32(a: emu_f64, b: f32) -> emu_f64 {
    let t0 = f64_two_prod(a.x, b);
    let t1 = f64_two_prod(a.y, b);
    let t2 = f64_two_prod(a.z, b);
    let p3 = a.w * b;
    let ts = f32_two_sum(t0.y, t1.x);
    let th = f32_three_sum(ts.y, t1.y, t2.x); // (s2, q1, p2)
    let u1 = f32_two_sum(th.y, t2.y);
    let u2 = f32_two_sum(p3, u1.x);
    return f32_quick_renorm(vec4<f32>(t0.x, ts.x, th.x, u2.x), (u1.y + u2.y) + th.z);
}

fn f64_div(a: emu_f64, b: emu_f64) -> emu_f64 {
    // Non-finite result (or divisor): the error-term arithmetic below would compute
    // Inf - Inf = NaN (Inf + 1 came out NaN). Return the IEEE result directly.
    let _nf = a.x / b.x;
    let _nf_hit = (bitcast<u32>(_nf) & 0x7F800000u) == 0x7F800000u || (bitcast<u32>(b.x) & 0x7F800000u) == 0x7F800000u;
    let q0 = a.x / b.x;
    var r = f64_sub(a, _f64_mul_f32(b, q0));
    
    let q1 = r.x / b.x;
    r = f64_sub(r, _f64_mul_f32(b, q1));
    
    let q2 = r.x / b.x;
    r = f64_sub(r, _f64_mul_f32(b, q2));
    
    let q3 = r.x / b.x;
    let qs1 = f64_add(f64_from_f32(q0), f64_from_f32(q1));
    let qs2 = f64_add(f64_from_f32(q2), f64_from_f32(q3));
    return select(f64_add(qs1, qs2), emu_f64(_nf, 0.0, 0.0, 0.0), _nf_hit);
}

// Ozaki emu_f64 comparisons - IEEE-strict NaN handling via bit pattern.
// See `_f32_is_nan_bits` in the Dekker section for rationale.
fn f64_lt(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x < b.x) || (a.x == b.x && a.y < b.y));
}

fn f64_le(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x < b.x) || (a.x == b.x && a.y <= b.y));
}

fn f64_gt(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x > b.x) || (a.x == b.x && a.y > b.y));
}

fn f64_ge(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && ((a.x > b.x) || (a.x == b.x && a.y >= b.y));
}

fn f64_eq(a: emu_f64, b: emu_f64) -> bool {
    return !(_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) && (a.x == b.x && a.y == b.y);
}

fn f64_ne(a: emu_f64, b: emu_f64) -> bool {
    return (_f32_is_nan_bits(a.x) || _f32_is_nan_bits(b.x)) || (a.x != b.x || a.y != b.y);
}

// Ozaki IEEE IsNaN / IsInfinity: bit-pattern checks, same as Dekker.
fn f64_is_nan(v: emu_f64) -> bool {
    return _f32_is_nan_bits(v.x);
}

fn f64_is_inf(v: emu_f64) -> bool {
    let bits = bitcast<u32>(v.x);
    return (bits & 0x7FFFFFFFu) == 0x7F800000u;
}

fn f64_abs(a: emu_f64) -> emu_f64 {
    return select(a, f64_neg(a), a.x < 0.0 || (a.x == 0.0 && a.y < 0.0));
}

fn f64_min(a: emu_f64, b: emu_f64) -> emu_f64 {
    return select(b, a, f64_lt(a, b));
}

fn f64_max(a: emu_f64, b: emu_f64) -> emu_f64 {
    return select(b, a, f64_gt(a, b));
}
" + F64ExactConversionFunctions + OzakiRoundingAndSqrtFunctions;

        #endregion

        #region f16 Emulation (Bit Conversion Helpers)

        /// <summary>
        /// WGSL helper functions for emulated Float16 when the browser does not expose
        /// the `shader-f16` feature. Arithmetic happens in native f32; the helpers only
        /// convert between the 16-bit IEEE 754 bit pattern (held in a u32) and f32 at
        /// buffer load/store boundaries. Storage layout is one Half per u32 (Option B).
        ///
        /// Behaviour matches the Wasm reference implementation
        /// (WasmKernelFunctionGenerator.cs EmitF16ToF32 / EmitF32ToF16) so the two
        /// emulated backends produce identical results for the same inputs.
        /// </summary>
        public const string F16Functions = @"
// ============================================================================
// Float16 Emulation Functions (16-bit IEEE 754 in u32, f32 arithmetic)
// ============================================================================

// Expand a 16-bit Float16 bit pattern (held in the low 16 bits of a u32)
// into a native f32 value. Denormals flush to signed zero.
fn _f16_to_f32(h: u32) -> f32 {
    let sign = (h >> 15u) & 1u;
    let exp  = (h >> 10u) & 0x1Fu;
    let mant = h & 0x3FFu;
    // exp == 0: zero or denormal - flush to signed zero
    if (exp == 0u) {
        return bitcast<f32>(sign << 31u);
    }
    // exp == 31: Inf or NaN - preserve sign, propagate mantissa into f32 NaN/Inf
    if (exp == 31u) {
        return bitcast<f32>((sign << 31u) | (0xFFu << 23u) | (mant << 13u));
    }
    // Normal: rebias exponent (-15 + 127 = +112), shift mantissa (10 -> 23 bits)
    return bitcast<f32>((sign << 31u) | ((exp + 112u) << 23u) | (mant << 13u));
}

// Compress a native f32 into the 16-bit Float16 bit pattern (returned in low 16
// bits of the u32). Underflow clamps to signed zero; overflow clamps to signed
// Inf while preserving mantissa bits so NaNs stay NaN.
fn _f32_to_f16(f: f32) -> u32 {
    // IEEE round-to-nearest-even f32 -> f16, incl subnormals + overflow-to-Inf. Bit-exact to
    // numpy/PyTorch/CUDA/OpenCL and the managed HalfConversion (von der Zijp truncation replaced).
    let bits = bitcast<u32>(f);
    let sign = (bits >> 16u) & 0x8000u;
    let rest = bits & 0x7FFFFFFFu;
    if (rest >= 0x7F800000u) {
        if (rest > 0x7F800000u) { return sign | 0x7E00u; }   // NaN
        return sign | 0x7C00u;                                // Inf
    }
    let e: i32 = i32((rest >> 23u) & 0xFFu) - 127;
    let f32Mant = rest & 0x7FFFFFu;
    if (e > 15) { return sign | 0x7C00u; }                    // overflow -> Inf
    if (e < -14) {
        if (e < -25) { return sign; }                          // -> +-0
        let signif = f32Mant | 0x800000u;
        let shift = u32((-14 - e) + 13);
        var m = signif >> shift;
        let roundBit = (signif >> (shift - 1u)) & 1u;
        let sticky = select(0u, 1u, (signif & ((1u << (shift - 1u)) - 1u)) != 0u);
        if (roundBit == 1u && (sticky == 1u || (m & 1u) == 1u)) { m = m + 1u; }
        return sign | m;
    }
    let mant10 = f32Mant >> 13u;
    let roundB = (f32Mant >> 12u) & 1u;
    let stick = select(0u, 1u, (f32Mant & 0xFFFu) != 0u);
    var outBits = (u32(e + 15) << 10u) | mant10;
    if (roundB == 1u && (stick == 1u || (mant10 & 1u) == 1u)) { outBits = outBits + 1u; }
    return sign | outBits;
}
";

        /// <summary>
        /// WGSL helpers that convert between the 16-bit bfloat16 bit pattern (held in the
        /// low 16 bits of a u32) and f32 at buffer load/store boundaries. bfloat16 is the
        /// top 16 bits of an fp32, so conversion is pure bit-shifting - no exponent rebias
        /// or table. Matches ILGPU.BFloat16's managed ConvertBFloat16ToFloat /
        /// ConvertFloatToBFloat16 (and the Wasm reference) byte-for-byte.
        /// </summary>
        public const string BF16Functions = @"
// ============================================================================
// BFloat16 Emulation Functions (top-16-bits-of-fp32 in u32, f32 arithmetic)
// ============================================================================

// Expand a 16-bit bfloat16 bit pattern (low 16 bits of a u32) into f32 by
// shifting it back into the high half of the fp32 encoding (exact).
fn _bf16_to_f32(h: u32) -> f32 {
    return bitcast<f32>((h & 0xFFFFu) << 16u);
}

// Compress a native f32 into the 16-bit bfloat16 bit pattern (low 16 bits of the
// u32) using round-to-nearest-even. NaN is preserved (a naive truncate could
// collapse some NaNs to Inf, so force a mantissa bit).
fn _f32_to_bf16(f: f32) -> u32 {
    let bits = bitcast<u32>(f);
    if ((bits & 0x7FFFFFFFu) > 0x7F800000u) {
        return ((bits >> 16u) | 0x0040u) & 0xFFFFu;
    }
    let lsb = (bits >> 16u) & 1u;
    let rounded = bits + 0x7FFFu + lsb;
    return (rounded >> 16u) & 0xFFFFu;
}
";

        /// <summary>
        /// FP8 (OCP E5M2 + E4M3FN) bit-conversion helpers. Both FP8 formats are always emulated
        /// (no native WGSL fp8). Direct WGSL ports of the managed ConvertFloat8E*M*ToFloat /
        /// ConvertFloatToFloat8E*M* (CPU-verified idempotence 0/256, and the OpenCL C twins are
        /// PMT-verified) so every representable value round-trips bit-identically. The raw 8-bit
        /// pattern lives in the low 8 bits of a u32; values compute as f32 in-register.
        /// </summary>
        public const string FP8Functions = @"
// ============================================================================
// FP8 Emulation Functions (E5M2 = 1/5/2 bias 15 IEEE-style; E4M3FN = 1/4/3 bias 7, no Inf, sat 448)
// ============================================================================

fn _e5m2_to_f32(raw: u32) -> f32 {
    let bits = raw & 0xFFu;
    let sign = (bits & 0x80u) << 24u;
    let expo = (bits >> 2u) & 0x1Fu;
    let mant = bits & 0x03u;
    if (expo == 0u) {
        if (mant == 0u) { return bitcast<f32>(sign); }
        var e: u32 = 127u - 15u + 1u;
        var m: u32 = mant;
        loop { if ((m & 0x04u) != 0u) { break; } m = m << 1u; e = e - 1u; }
        m = m & 0x03u;
        return bitcast<f32>(sign | (e << 23u) | (m << 21u));
    }
    if (expo == 0x1Fu) { return bitcast<f32>(sign | (0xFFu << 23u) | (mant << 21u)); }
    let f32Exp = expo - 15u + 127u;
    return bitcast<f32>(sign | (f32Exp << 23u) | (mant << 21u));
}

fn _f32_to_e5m2(f: f32) -> u32 {
    let bits = bitcast<u32>(f);
    let sign = (bits >> 24u) & 0x80u;
    let rest = bits & 0x7FFFFFFFu;
    if (rest > 0x7F800000u) { return sign | 0x7Fu; }
    if (rest == 0x7F800000u) { return sign | 0x7Cu; }
    let f32Exp = i32((rest >> 23u) & 0xFFu);
    let f32Mant = rest & 0x7FFFFFu;
    let e = f32Exp - 127;
    if (e > 15) { return sign | 0x7Cu; }
    if (e < -14) {
        if (f32Exp == 0) { return sign; }
        let signif = f32Mant | 0x800000u;
        let shift = (-14 - e) + 21;
        if (shift > 31) { return sign; }
        var m: u32 = signif >> u32(shift);
        let roundBit = (signif >> u32(shift - 1)) & 1u;
        let sticky = select(0u, 1u, (signif & ((1u << u32(shift - 1)) - 1u)) != 0u);
        if (roundBit == 1u && (sticky == 1u || (m & 1u) == 1u)) { m = m + 1u; }
        return sign | (m & 0x03u) | ((m >> 2u) << 2u);
    }
    let mant2 = f32Mant >> 21u;
    let roundB = (f32Mant >> 20u) & 1u;
    let stick = select(0u, 1u, (f32Mant & 0xFFFFFu) != 0u);
    let eField = u32(e + 15);
    var outBits: u32 = (eField << 2u) | mant2;
    if (roundB == 1u && (stick == 1u || (mant2 & 1u) == 1u)) { outBits = outBits + 1u; }
    return sign | (outBits & 0x7Fu);
}

fn _e4m3_to_f32(raw: u32) -> f32 {
    let bits = raw & 0xFFu;
    let sign = (bits & 0x80u) << 24u;
    let expo = (bits >> 3u) & 0x0Fu;
    let mant = bits & 0x07u;
    if ((bits & 0x7Fu) == 0x7Fu) { return bitcast<f32>(sign | 0x7FC00000u); }
    if (expo == 0u) {
        if (mant == 0u) { return bitcast<f32>(sign); }
        var e: u32 = 127u - 7u + 1u;
        var m: u32 = mant;
        loop { if ((m & 0x08u) != 0u) { break; } m = m << 1u; e = e - 1u; }
        m = m & 0x07u;
        return bitcast<f32>(sign | (e << 23u) | (m << 20u));
    }
    let f32Exp = expo - 7u + 127u;
    return bitcast<f32>(sign | (f32Exp << 23u) | (mant << 20u));
}

fn _f32_to_e4m3(f: f32) -> u32 {
    let bits = bitcast<u32>(f);
    let sign = (bits >> 24u) & 0x80u;
    let rest = bits & 0x7FFFFFFFu;
    if (rest >= 0x7F800000u) { return sign | 0x7Fu; }
    let f32Exp = i32((rest >> 23u) & 0xFFu);
    let f32Mant = rest & 0x7FFFFFu;
    let e = f32Exp - 127;
    if (e > 8) { return sign | 0x7Fu; } // fn: e>8 unconditional overflow -> NaN; e==8 rounds below
    if (e < -6) {
        if (f32Exp == 0) { return sign; }
        let signif = f32Mant | 0x800000u;
        let shift = (-6 - e) + 20;
        if (shift > 31) { return sign; }
        var m: u32 = signif >> u32(shift);
        let roundBit = (signif >> u32(shift - 1)) & 1u;
        let sticky = select(0u, 1u, (signif & ((1u << u32(shift - 1)) - 1u)) != 0u);
        if (roundBit == 1u && (sticky == 1u || (m & 1u) == 1u)) { m = m + 1u; }
        return sign | (m & 0x7Fu);
    }
    let mant3 = f32Mant >> 20u;
    let roundB = (f32Mant >> 19u) & 1u;
    let stick = select(0u, 1u, (f32Mant & 0x7FFFFu) != 0u);
    let eField = u32(e + 7);
    var outBits: u32 = (eField << 3u) | mant3;
    if (roundB == 1u && (stick == 1u || (mant3 & 1u) == 1u)) { outBits = outBits + 1u; }
    if (outBits >= 0x7Fu) { outBits = 0x7Fu; } // fn: full outBits (incl 0x80 carry) reaching the 0x7F slot -> NaN
    return sign | (outBits & 0x7Fu);
}
";

        /// <summary>
        /// FP4 (OCP E2M1FN) bit-conversion helpers. Always emulated (no native WGSL fp4).
        /// Direct WGSL port of the managed ConvertFloat4E2M1ToFloat / ConvertFloatToFloat4E2M1
        /// (CPU-verified bit-exact to ml_dtypes.float4_e2m1fn; the OpenCL C twins
        /// _e2m1_bits_to_f32 / _f32_to_e2m1_bits are PMT-verified) so every representable value
        /// round-trips bit-identically. 16 finite codes, NO Inf, NO NaN; magnitudes
        /// {0,.5,1,1.5,2,3,4,6}, max 6. The 4-bit value lives in the LOW NIBBLE of an 8-bit
        /// storage element; the raw byte sits in the low 8 bits of a u32. Sign = bit 3 (0x8).
        /// finite overflow AND +-Inf saturate to +-6 (0x7/0xF); NaN -> -0 (0x8).
        /// </summary>
        public const string FP4Functions = @"
// ============================================================================
// FP4 Emulation Functions (E2M1FN = 1/2/1 bias 1; no Inf/NaN; mags {0,.5,1,1.5,2,3,4,6}; value in low nibble)
// ============================================================================

fn _e2m1_to_f32(raw: u32) -> f32 {
    let code = raw & 0x0Fu;
    let sign = (code & 0x8u) << 28u;
    let e = (code >> 1u) & 0x3u;
    let m = code & 0x1u;
    if (e == 0u) {
        if (m == 0u) { return bitcast<f32>(sign); }
        return bitcast<f32>(sign | (126u << 23u)); // subnormal 0.5
    }
    let f32Exp = e - 1u + 127u;
    return bitcast<f32>(sign | (f32Exp << 23u) | (m << 22u));
}

fn _f32_to_e2m1(f: f32) -> u32 {
    let bits = bitcast<u32>(f);
    let sign = (bits >> 28u) & 0x8u;
    let rest = bits & 0x7FFFFFFFu;
    if (rest > 0x7F800000u) { return 0x8u; }          // NaN -> -0
    if (rest >= 0x7F800000u) { return sign | 0x7u; }  // +-Inf -> +-6
    let f32Exp = i32((rest >> 23u) & 0xFFu);
    let f32Mant = rest & 0x7FFFFFu;
    let e = f32Exp - 127;
    if (e > 2) { return sign | 0x7u; }                // finite overflow -> +-6
    if (e < 0) {
        if (f32Exp == 0) { return sign; }             // +-0
        let signif = f32Mant | 0x800000u;
        let shift = (-1 - e) + 23;
        if (shift > 31) { return sign; }              // underflow -> +-0
        var q: u32 = signif >> u32(shift);
        let roundBit = (signif >> u32(shift - 1)) & 1u;
        let sticky = select(0u, 1u, (signif & ((1u << u32(shift - 1)) - 1u)) != 0u);
        if (roundBit == 1u && (sticky == 1u || (q & 1u) == 1u)) { q = q + 1u; }
        return sign | (q & 0x7u);
    }
    let mant1 = f32Mant >> 22u;
    let round = (f32Mant >> 21u) & 1u;
    let stick = select(0u, 1u, (f32Mant & 0x1FFFFFu) != 0u);
    let eField = u32(e + 1);
    var outBits: u32 = (eField << 1u) | mant1;
    if (round == 1u && (stick == 1u || (mant1 & 1u) == 1u)) { outBits = outBits + 1u; }
    if (outBits > 0x7u) { outBits = 0x7u; }           // carry past +-6 saturates (no larger finite/Inf)
    return sign | (outBits & 0x7u);
}
";

        #endregion

        #region Combined Library

        /// <summary>
        /// Gets the full emulation library based on which features are enabled.
        /// Overload that defaults <c>includeF16</c> to false for source compatibility.
        /// </summary>
        public static string GetEmulationLibrary(bool includeF64, bool useOzakiF64, bool includeI64)
            => GetEmulationLibrary(includeF64, useOzakiF64, includeI64, includeF16: false);

        /// <summary>
        /// Gets the full emulation library based on which features are enabled.
        /// </summary>
        /// <param name="includeF16">When true, emits the Float16 bit-conversion helpers
        /// (<c>_f16_to_f32</c>, <c>_f32_to_f16</c>). Required when the kernel touches
        /// Float16 and the browser lacks the <c>shader-f16</c> feature.</param>
        public static string GetEmulationLibrary(bool includeF64, bool useOzakiF64, bool includeI64, bool includeF16, bool includeBF16 = false)
        {
            var sb = new System.Text.StringBuilder();

            if (includeF64)
            {
                if (useOzakiF64)
                {
                    sb.AppendLine(OzakiF64TypeAlias);
                    sb.AppendLine(OzakiF64Functions);
                }
                else
                {
                    sb.AppendLine(F64TypeAlias);
                    sb.AppendLine(F64Functions);
                }
            }

            if (includeI64)
            {
                sb.AppendLine(I64TypeAlias);
                sb.AppendLine(U64TypeAlias);
                sb.AppendLine(I64Functions);
            }

            if (includeF16)
            {
                sb.AppendLine(F16Functions);
            }

            if (includeBF16)
            {
                sb.AppendLine(BF16Functions);
            }

            return sb.ToString();
        }

        #endregion

        #region Minimal Library (Per-Function Trimming)

        private record EmulationFunc(string Name, string Code);

        private static readonly List<EmulationFunc> _dekkerF64Funcs;
        private static readonly List<EmulationFunc> _ozakiF64Funcs;
        private static readonly List<EmulationFunc> _i64Funcs;
        private static readonly List<EmulationFunc> _f16Funcs;
        private static readonly List<EmulationFunc> _bf16Funcs;
        private static readonly List<EmulationFunc> _fp8Funcs;
        private static readonly List<EmulationFunc> _fp4Funcs;
        private static readonly Dictionary<string, HashSet<string>> _dekkerF64Deps;
        private static readonly Dictionary<string, HashSet<string>> _ozakiF64Deps;
        private static readonly Dictionary<string, HashSet<string>> _i64Deps;
        private static readonly Dictionary<string, HashSet<string>> _f16Deps;
        private static readonly Dictionary<string, HashSet<string>> _bf16Deps;
        private static readonly Dictionary<string, HashSet<string>> _fp8Deps;
        private static readonly Dictionary<string, HashSet<string>> _fp4Deps;

        static WGSLEmulationLibrary()
        {
            _dekkerF64Funcs = SplitIntoFunctions(F64Functions);
            _ozakiF64Funcs = SplitIntoFunctions(OzakiF64Functions);
            _i64Funcs = SplitIntoFunctions(I64Functions);
            _f16Funcs = SplitIntoFunctions(F16Functions);
            _bf16Funcs = SplitIntoFunctions(BF16Functions);
            _fp8Funcs = SplitIntoFunctions(FP8Functions);
            _fp4Funcs = SplitIntoFunctions(FP4Functions);
            _dekkerF64Deps = BuildDependencies(_dekkerF64Funcs);
            _ozakiF64Deps = BuildDependencies(_ozakiF64Funcs);
            _i64Deps = BuildDependencies(_i64Funcs);
            _f16Deps = BuildDependencies(_f16Funcs);
            _bf16Deps = BuildDependencies(_bf16Funcs);
            _fp8Deps = BuildDependencies(_fp8Funcs);
            _fp4Deps = BuildDependencies(_fp4Funcs);
        }

        /// <summary>
        /// Gets a minimal emulation library containing only the functions actually
        /// used by the kernel body, plus their transitive dependencies.
        /// Overload that defaults <c>includeF16</c> to false for source compatibility.
        /// </summary>
        public static string GetMinimalEmulationLibrary(
            bool includeF64, bool useOzakiF64, bool includeI64,
            string kernelBody)
            => GetMinimalEmulationLibrary(includeF64, useOzakiF64, includeI64, includeF16: false, kernelBody);

        /// <summary>
        /// Gets a minimal emulation library containing only the functions actually
        /// used by the kernel body, plus their transitive dependencies.
        /// Scans <paramref name="kernelBody"/> for emulation function calls and
        /// includes only the needed subset, preserving dependency order.
        /// </summary>
        /// <param name="includeF16">When true, considers the Float16 bit-conversion
        /// helpers (<c>_f16_to_f32</c>, <c>_f32_to_f16</c>) for inclusion. Each is
        /// emitted only if the kernel body actually calls it.</param>
        public static string GetMinimalEmulationLibrary(
            bool includeF64, bool useOzakiF64, bool includeI64, bool includeF16,
            string kernelBody, bool includeBF16 = false, bool includeFP8 = false,
            bool includeFP4 = false)
        {
            var sb = new System.Text.StringBuilder();

            // Per-family decision: minimal-trim by kernelBody text-scan only when
            // the family's call sites are guaranteed to appear in `kernelBody`. F64
            // and I64 emulation function calls (`i64_ge`, `i64_eq`, `f64_add` etc.)
            // can be emitted by HELPER fn bodies — and at GenerateHeader time the
            // kernel main `Builder` does NOT yet contain the helper fn bodies (those
            // get Merge()d in AFTER GenerateHeader runs). The text-scan would miss
            // those calls and skip the corresponding fn defs, producing the WGSL
            // validator's "called but not defined" error (Tuvok's 2026-05-05 AV1
            // walker `i64_ge` / `i64_eq` symptom). For correctness, include ALL
            // funcs in those families when the flag is on. The total size is tiny
            // (~50 lines of i64 + ~30 of f64) compared to the kernel itself, and
            // the validator-reject hazard outweighs the minor binary-size win from
            // trimming.
            if (includeF64)
            {
                var funcs = useOzakiF64 ? _ozakiF64Funcs : _dekkerF64Funcs;
                sb.AppendLine(useOzakiF64 ? OzakiF64TypeAlias : F64TypeAlias);
                foreach (var func in funcs)
                {
                    sb.AppendLine(func.Code);
                    sb.AppendLine();
                }
            }

            if (includeI64)
            {
                sb.AppendLine(I64TypeAlias);
                sb.AppendLine(U64TypeAlias);
                foreach (var func in _i64Funcs)
                {
                    sb.AppendLine(func.Code);
                    sb.AppendLine();
                }
            }

            if (includeF16)
            {
                // F16 helpers stay on the minimal-trim path because:
                //   - The set is small (3 funcs) and dependency-shallow.
                //   - F16 calls in helpers appear at LEA / Load / Store of sub-word
                //     ArrayView<Half> params — those are OWNED by the helper-side
                //     codegen path I added in WGSLFunctionGenerator (rc.16 Bug D
                //     phase 2), which sets `_kernelReferencesF16Helpers` on the
                //     SHARED instance flag accessor used by needsF16Emulation
                //     determination upstream (lines 1218-1220 of
                //     WGSLKernelFunctionGenerator). So the includeF16 flag
                //     itself is correctly raised; trimming the unused subset
                //     stays safe.
                AppendUsedFunctions(sb, _f16Funcs, _f16Deps, kernelBody);
            }

            if (includeBF16)
            {
                // bfloat16 helpers (_bf16_to_f32 / _f32_to_bf16) — same minimal-trim path
                // as f16: emitted only when the kernel/helper body references them, with
                // includeBF16 raised by needsBF16Emulation upstream.
                AppendUsedFunctions(sb, _bf16Funcs, _bf16Deps, kernelBody);
            }

            if (includeFP8)
            {
                // FP8 helpers (_e4m3/_e5m2 <-> f32) - same minimal-trim path as bf16; emitted
                // only when the kernel/helper body references them, includeFP8 raised by
                // needsFP8Emulation upstream.
                AppendUsedFunctions(sb, _fp8Funcs, _fp8Deps, kernelBody);
            }

            if (includeFP4)
            {
                // FP4 helpers (_e2m1 <-> f32) - same minimal-trim path as FP8; emitted
                // only when the kernel/helper body references them, includeFP4 raised by
                // needsFP4Emulation upstream.
                AppendUsedFunctions(sb, _fp4Funcs, _fp4Deps, kernelBody);
            }

            return sb.ToString();
        }

        /// <summary>
        /// Splits a WGSL library source string into individual function entries.
        /// Each entry includes the function's preceding comment lines.
        /// </summary>
        private static List<EmulationFunc> SplitIntoFunctions(string library)
        {
            var result = new List<EmulationFunc>();
            var lines = library.Split('\n');

            // First pass: find all function definition lines
            var funcPositions = new List<(int LineIndex, string Name)>();
            for (int i = 0; i < lines.Length; i++)
            {
                var trimmed = lines[i].TrimStart();
                if (trimmed.StartsWith("fn "))
                {
                    int nameEnd = trimmed.IndexOf('(', 3);
                    if (nameEnd < 0) continue;
                    string name = trimmed.Substring(3, nameEnd - 3).Trim();
                    funcPositions.Add((i, name));
                }
            }

            // Second pass: extract each function with its preceding comment block
            for (int fi = 0; fi < funcPositions.Count; fi++)
            {
                var (fnLine, name) = funcPositions[fi];

                // Back up to include preceding comment lines (skip section headers "// ====")
                int commentStart = fnLine;
                while (commentStart > 0)
                {
                    var prev = lines[commentStart - 1].TrimStart();
                    if (prev.StartsWith("//") && !prev.StartsWith("// ===="))
                        commentStart--;
                    else
                        break;
                }

                // Find closing brace via depth tracking
                int braceDepth = 0;
                bool seenBrace = false;
                int funcEnd = fnLine;
                for (int j = fnLine; j < lines.Length; j++)
                {
                    foreach (char c in lines[j])
                    {
                        if (c == '{') { braceDepth++; seenBrace = true; }
                        else if (c == '}') braceDepth--;
                    }
                    if (seenBrace && braceDepth == 0)
                    {
                        funcEnd = j;
                        break;
                    }
                }

                // Build function code string
                var funcSb = new System.Text.StringBuilder();
                for (int j = commentStart; j <= funcEnd; j++)
                {
                    if (j > commentStart) funcSb.Append('\n');
                    funcSb.Append(lines[j]);
                }

                result.Add(new EmulationFunc(name, funcSb.ToString()));
            }

            return result;
        }

        /// <summary>
        /// Builds a dependency graph by scanning each function's code for calls
        /// to other known function names in the same library.
        /// </summary>
        private static Dictionary<string, HashSet<string>> BuildDependencies(
            List<EmulationFunc> funcs)
        {
            var allNames = new HashSet<string>();
            foreach (var func in funcs) allNames.Add(func.Name);

            var deps = new Dictionary<string, HashSet<string>>();
            foreach (var func in funcs)
            {
                var funcDeps = new HashSet<string>();
                foreach (var name in allNames)
                {
                    if (name != func.Name && func.Code.Contains(name + "("))
                        funcDeps.Add(name);
                }
                deps[func.Name] = funcDeps;
            }
            return deps;
        }

        /// <summary>
        /// Scans the kernel body for calls to emulation functions, resolves
        /// transitive dependencies, and appends only the needed functions
        /// to the StringBuilder in dependency order.
        /// </summary>
        private static void AppendUsedFunctions(
            System.Text.StringBuilder sb,
            List<EmulationFunc> funcs,
            Dictionary<string, HashSet<string>> deps,
            string kernelBody)
        {
            // Find directly used functions
            var needed = new HashSet<string>();
            foreach (var func in funcs)
            {
                if (kernelBody.Contains(func.Name + "("))
                    needed.Add(func.Name);
            }

            // Add transitive dependencies (BFS)
            var toProcess = new Queue<string>(needed);
            while (toProcess.Count > 0)
            {
                var name = toProcess.Dequeue();
                if (deps.TryGetValue(name, out var funcDeps))
                {
                    foreach (var dep in funcDeps)
                    {
                        if (needed.Add(dep))
                            toProcess.Enqueue(dep);
                    }
                }
            }

            // Emit in original order (which is dependency order)
            foreach (var func in funcs)
            {
                if (needed.Contains(func.Name))
                {
                    sb.AppendLine(func.Code);
                    sb.AppendLine();
                }
            }
        }

        #endregion
    }
}
